### ISSUE TITLE
QC inputs

### ISSUE THREAD

**Issue by cjfields** [h3abionet/HPCBio-Refgraph_pipeline#10]

**Comment by grendon** [comment]
At least one of the cram files appears to be truncated.  

I renamed it from "NA19247.final.cram"  to  "NA19247.final.cram.truncated" in order to force the pipeline to skip this file.  It is a temporary solution.  

A more permanent solution would be to include a sanity check in the code when the cram file is read and processed.

**Comment by cjfields** [comment]
This might be a QC step to add (can assign during the hackathon).

**Comment by grendon** [comment]
We could check if samtools could not read the cram file. The code would look like this:

<pre>
    script:
    if(params.singleEnd){
    """
    samtools view -bt ${index} -S -b -f 4 ${name} > ${name.baseName}.unmap.bam
    if [ -s \${name.baseName}.unmap.bam ]
    then
	 samtools fastq -f 4 ${name.baseName}.unmap.bam > ${name.baseName}_SE_R1.fastq
    fi

    
    """
    } else {
    """
    samtools view -bt ${index} -S -b -f 4 ${name} > ${name.baseName}.unmap.bam
    if [ -s \${name.baseName}.unmap.bam ]
    then
         samtools fastq -f 12 ${name.baseName}.unmap.bam -1 ${name.baseName}_PE_R1.fastq -2 ${name.baseName}_PE_R2.fastq
    fi
    """ 

</pre>

But, I need to wait until I am done with all Yoruba samples before updating the code; otherwise the pipeline will start all over again.

**Comment by grendon** [comment]
I just tested the code I outlined in my previous posting and... It did not work.  

yes the samtools cmd detected the truncated file
no, the job did not exit gracefully  because it aborted the job and made the nextflow hung.

Bottom line: a separate process needs to be added to perform QC of the input file before executing the extract_unmap process

Gory details:

The execution printed this msg to the screen. But it should have happened in the first place 
because the process has the value "validExitStatus        0,1"

<pre>
WARN: Killing pending tasks (2)
Error executing process > 'extract_unmap (/home/groups/h3abionet/RefGraph/data/tiny4test/NA18499.truncated.cram)'

Caused by:
  Missing output file(s) `*` expected by process `extract_unmap (/home/groups/h3abionet/RefGraph/data/tiny4test/NA18499.truncated.cram)`

Command executed:

  samtools view -bt GRCh38_full_analysis_set_plus_decoy_hla.fa.fai -S -b -f 4 /home/groups/h3abionet/RefGraph/data/tiny4test/NA18499.truncated.cram > NA18499.truncated.unmap.bam
  if [ -s NA18499.truncated.unmap.bam ]
  then
       samtools fastq -f 12 NA18499.truncated.unmap.bam -1 NA18499.truncated_PE_R1.fastq -2 NA18499.truncated_PE_R2.fastq
  fi
  #samtools fastq -f 68 -F 8 NA18499.truncated.unmap.bam > NA18499.truncated_SE_R1.fastq
  #samtools fastq -f 132 -F 8 NA18499.truncated.unmap.bam > NA18499.truncated_SE_R2.fastq

Command exit status:
  1

Command output:
  (empty)

Command error:
  [main_samview] truncated file.

Work dir:
  /home/groups/h3abionet/RefGraph/src/work/40/5f54e41bae27a5a5d58c0b3d8bd971

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

</pre>

This is the code of the process that generated the above error msg

<pre>

process extract_unmap {
    tag                    { name }
    executor               myExecutor
    clusterOptions         params.clusterAcct 
    cpus                   defaultCPU
    queue                  params.myQueue
    memory                 "$defaultMemory GB"
    module                 params.samtoolsMod
    publishDir             readPrepPath, mode: "copy"	    
    validExitStatus        0,1
    errorStrategy          'finish'
    scratch                '/scratch'
    stageOutMode           'copy'
    
    input:
    set val(name), file(CRAM) from CRAM_Ch1	
    file genome from genome_file
    file index from genome_index_ch

    output:
    set val(name), file('*.fastq') optional true into fq_ch
    file '*'
    
    script:
    if(params.singleEnd){
    """
    samtools view -bt ${index} -S -b -f 4 ${name} > ${name.baseName}.unmap.bam
    if [ -s ${name.baseName}.unmap.bam ]
    then
	 samtools fastq -f 4 ${name.baseName}.unmap.bam > ${name.baseName}_SE_R1.fastq
    fi
    """
    } else {
    """
    samtools view -bt ${index} -S -b -f 4 ${name} > ${name.baseName}.unmap.bam
    if [ -s ${name.baseName}.unmap.bam ]
    then
         samtools fastq -f 12 ${name.baseName}.unmap.bam -1 ${name.baseName}_PE_R1.fastq -2 ${name.baseName}_PE_R2.fastq
    fi
    #samtools fastq -f 68 -F 8 ${name.baseName}.unmap.bam > ${name.baseName}_SE_R1.fastq
    #samtools fastq -f 132 -F 8 ${name.baseName}.unmap.bam > ${name.baseName}_SE_R2.fastq
    """    
    }

}


</pre>

**Comment by cjfields** [comment]
I think the second output (`file '*'`) also has to be optional.

**Comment by grendon** [comment]
added qc_input process to check cram files
